{% set version = "0.0.51" %}

package:
  name: singularity-hpc
  version: {{ version }}

source:
  url: https://github.com/singularityhub/singularity-hpc/archive/refs/tags/{{ version }}.tar.gz
  sha256: a9ccb22655fa8058ef90bb4e92f3065539abbd0d9be2170ebcbdfdf551722bb8


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shpc = shpc.client:run_shpc
requirements:
  host:
    - python >=3.6
    - pip
    - spython >=0.1.13
    - jinja2
    - jsonschema
    - ruamel.yaml
    - pytest-runner
    - pytest =>4.6.2
  run:
    - python >=3.6

test:
  source_files:
    - shpc/
    - shpc/tests
  requires:
    - pytest
    - ruamel.yaml
    - jsonschema
    - jinja2
  commands:
    - shpc --help

about:
  home: https://singularity-hpc.readthedocs.io
  license: MPL-2.0
  license_file: LICENSE
  summary: Local filesystem registry for containers (intended for HPC) using Lmod or Environement Modules. Works for users and admins.
  doc_url: https://singularity-hpc.readthedocs.io/en/latest/index.html
  dev_url: https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html

  description: |
    Singularity Registry HPC (shpc) allows you to install containers as modules. 
    Currently, this includes: Lmod and Environment Modules.
     
    And container technologies:
      Singularity,
      Podman, and
      Docker.

    And coming soon:
      Shifter and
      Sarus.

    You can use shpc if you are:
      a linux administrator wanting to manage containers as modules for your cluster,
      a cluster user that wants to maintain your own folder of custom modules, or
      a cluster user that simply wants to pull Singularity images as GitHub packages.

    The library contains a collection of module recipes that will install containers, 
    so you can easily use them or write your own. To see the code, head over to the repository. 
    To browse modules available as containers, see the library.

extra:
  recipe-maintainers:
    - ngam
    - vsoch
